package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "batchprogramming")
@EqualsAndHashCode(callSuper = false)
public class Batchprogramming extends BasePO {

    private static final long serialVersionUID = 1L;

    private Integer idtype;
    private String value;
    private Date dateprogramming;
    private Date dateadded;
    private Date datecancelled;
    private Integer status;

}