package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "catalog_comercio")
@EqualsAndHashCode(callSuper = false)
public class CatalogComercio extends BasePO {

    private static final long serialVersionUID = 1L;

    private String codigoAfiliacion;
    private String merchantidc;
    private String nombreComercial;
    private String nombreLegal;
    private String rtn;
    private String gerente;
    private String fechaAfiliacion;
    private String direccion;
    private String telefono;
    private String ciudad;
    private String ejecutivo;
    private String zona;

}