package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "departamentos")
@EqualsAndHashCode(callSuper = false)
public class Departamentos extends BasePO {

    private static final long serialVersionUID = 1L;

    private String iddepartamento;
    private String departamento;
    private Integer idmunicipio;
    private String municipio;
    private Integer zona;

}