package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "historialdescargaparametros")
@EqualsAndHashCode(callSuper = false)
public class Historialdescargaparametros extends BasePO {

    private static final long serialVersionUID = 1L;

    private String terminalid;
    private String nombreapp;
    private String version;
    private Date fechadescarga;
    private Long jsondata;

}