package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "profile_user")
@EqualsAndHashCode(callSuper = false)
public class ProfileUser extends BasePO {

    private static final long serialVersionUID = 1L;

    @Id
    private Integer idProfile;
    private String description;
    private String nameProfile;

}