package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "sendalarm")
@EqualsAndHashCode(callSuper = false)
public class Sendalarm extends BasePO {

    private static final long serialVersionUID = 1L;

    private String typealarm;
    private String frecuencia;
    private String email;
    private Date fechainicio;
    private Date fechafin;
    private Integer hora;

}