package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "terminales")
@EqualsAndHashCode(callSuper = false)
public class Terminales extends BasePO {

    private static final long serialVersionUID = 1L;

    private String noinventario;
    private String noserie;
    private String partnumber;
    private Integer idmodelo;
    private String merchantid;
    private String terminalid;
    private Integer idtipodeconexion;
    private String versiondesoftware;
    private Integer idestatus;
    private Date fecharegistro;
    private Date fechainstalacion;
    private Integer idcarrier;
    private String numerochip;
    private String telefonodecontacto;
    private String nombrepersonalacargo;
    private String nombredeltecnico;
    private String nofacturadoramanual;
    private Short fuentepodertransformador;
    private Short adaptadoresdoblepuerto;
    private Short cabletelefonico;
    private Short cablered;
    private Short rollospapel;
    private Short comprobantes;
    private Short remisiones;
    private Short materialpop;
    private Short kitpromocionales;
    private Short manuales;
    private String notas;
    private Date fechaultimamodificacion;
    private String usuariomodifico;
    private String versioneos;
    private String versionemv;
    private String versionos;
    private String apn;
    private String ip;
    private Integer idbrand;
    private Date fechaultimainicializacion;
    private Integer tipoinicializacion;
    private String revisionhw;
    private String countrycode;
    private Integer idconfigparametros;
    private Date ultimadescargaparametros;
    private Date ultimadescargasoftware;

}