package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "terminal_alarm")
@EqualsAndHashCode(callSuper = false)
public class TerminalAlarm extends BasePO {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTerminalAlarm;
    private String terminalidalarm;
    private Integer idTerminal;
    private Integer idTypeAlarm;
    private Integer idTerminalTransaction;
    private Date dateAdded;
    private Date dateAttended;
    private Integer idEstatus;
    private String usuario;

}