package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "terminal_statistics")
@EqualsAndHashCode(callSuper = false)
public class TerminalStatistics extends BasePO {

    private static final long serialVersionUID = 1L;

    private Integer idTerminal;
    private String terminalid;
    private String acquier;
    private Integer contadorVenta;
    private Integer contadorReversos;
    private Integer contadorDevolucion;
    private Integer contadorCancelaciones;
    private Integer contadorAprobadas;
    private Integer contadorDenegadas;
    private Integer contadorEmv;
    private Integer contadorManual;
    private Integer contadorBanda;
    private Integer contadorContactless;
    private Integer contadorFailback;
    private BigDecimal montoBase;
    private BigDecimal montoAnulado;
    private BigDecimal montoDevoluciones;
    private BigDecimal montoReversado;
    private BigDecimal montoEfectivo;
    private BigDecimal montoImpuesto;
    private BigDecimal impuestoAdicional;
    private BigDecimal descuentoImpuesto;
    private BigDecimal descuentoAtlantida;
    private BigDecimal montoPropina;
    private String currency;
    private Integer contadorConexionesIpprimaria;
    private Integer contadorConexionesIpsecundaria;
    private Integer contadorConexionesDialprimario;
    private Integer contadorConexionesDialsecundario;
    private Integer nivelGprs;
    private Integer errorConexion;
    private Integer errorEnvio;
    private Integer errorRecepcion;
    private Date fecha;

}