package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "terminal_transactions")
@EqualsAndHashCode(callSuper = false)
public class TerminalTransactions extends BasePO {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTerminalTransaction;
    private Integer idTerminal;
    private Integer idTerminalProgramming;
    private String geolocalitation;
    private Date dateTransaction;
    private String comunicationType;
    private Integer idStatusTransaction;
    private Integer idTypeMessage;
    private Integer idMessageId;

}