package com.mx.controlpos.mpos.data.domain;

import javax.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import test.BasePO;

/**
 * Auto generated by jpa-maven-plugin
 * @author user
 * @date 2019-01-15 10:09:33
 */
@Data
@Entity
@Table(name = "user")
@EqualsAndHashCode(callSuper = false)
public class User extends BasePO {

    private static final long serialVersionUID = 1L;

    @Id
    private Integer idUser;
    private String email;
    private Integer idProfile;
    private String image;
    private String name;
    private String nickName;
    private String password;
    private String surname;

}